stages:
  - model_expand
  - model_detect

  - CompoMe_Core
  - CompoMe_Opt
  - CompoMe_Link

  - cpp_clang
  - cpp_example
  - graph
  - uml
  - python

variables:
  CXX: "clang++"
  TERM: xterm

# ######################UML
include:
  - local: '/.gitlab-ci_model.yaml'
  - local: '/.gitlab-ci_core.yaml'
  - local: '/.gitlab-ci_cpp.yaml'
  - local: '/.gitlab-ci_graph.yaml'
  - local: '/.gitlab-ci_uml.yaml'
  - local: '/.gitlab-ci_python.yaml'
