# #####################PYTHON
python_TYPE:
  stage: python
  needs: ["CompoMe_Core", "CompoMe_Test", "CompoMe_Dbus", "CompoMe_Json"]
  retry: 2
  tags:
    - python
  script:
    - export COMPO_WORKDIR_TMP=1 
    - cd Test/gen/
    - ./run_test.sh python 1.TYPE

python_ERROR:
  stage: python
  needs: ["CompoMe_Core", "CompoMe_Test", "CompoMe_Json"]
  retry: 2
  tags:
    - python
  script:
    - export COMPO_WORKDIR_TMP=1 
    - cd Test/gen/
    - ./run_test.sh python 1.ERROR

python_STRUCT:
  stage: python
  needs: ["CompoMe_Core", "CompoMe_Dbus", "CompoMe_Test", "CompoMe_Json"]
  retry: 2
  tags:
    - python
  script:
    - export COMPO_WORKDIR_TMP=1 
    - cd Test/gen/
    - ./run_test.sh python 1.STRUCT

python_INTERFACE:
  stage: python
  needs: ["CompoMe_Core", "CompoMe_Dbus", "CompoMe_Test", "CompoMe_Json"]
  retry: 2
  tags:
    - python
  script:
    - export COMPO_WORKDIR_TMP=1 
    - cd Test/gen/
    - ./run_test.sh python 2.INTERFACE

python_COMPONENT:
  stage: python
  needs: ["CompoMe_Core", "CompoMe_Test"]
  retry: 2
  tags:
    - python
  script:
    - export COMPO_WORKDIR_TMP=1 
    - cd Test/gen/
    - ./run_test.sh python 3.COMPONENT

python_DEPLOYMENT:
  stage: python
  needs: ["CompoMe_Core", "CompoMe_Test"]
  retry: 2
  tags:
    - python
  script:
    - export COMPO_WORKDIR_TMP=1
    - cd Test/gen/
    - ./run_test.sh python 5.DEPLOYMENT
