stages:
  - cpp
  - graph
  - uml
  - other

cpp_TYPE:
  stage: cpp
  tags:
    - python
  script:
    - cd Test/gen/
    - sh ./run_test2.sh cpp 1.TYPE

cpp_CONNECTOR:
  stage: cpp
  tags:
    - python
  script:
    - cd Test/gen/
    - sh ./run_test2.sh cpp 3.CONNECTOR

python_full:
  stage: other
  tags:
    - python
  script:
    - cd Test/gen/
    - sh ./run_test2.sh python

cpp_IMPORT:
  stage: cpp
  tags:
    - python
  script:
    - cd Test/gen/
    - sh ./run_test2.sh cpp 7.IMPORT

uml_TYPE:
  stage: uml
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test2.sh uml 1.TYPE

graph_TYPE:
  stage: graph
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test2.sh graph 1.TYPE


cpp_STRUCT:
  stage: cpp
  tags:
    - python
  script:
    - cd Test/gen/
    - sh ./run_test2.sh cpp 1.STRUCT

uml_STRUCT:
  stage: uml
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test2.sh uml 1.STRUCT

graph_STRUCT:
  stage: graph
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test2.sh graph 1.STRUCT

cpp_INTERFACE:
  stage: cpp
  tags:
    - python
  script:
    - cd Test/gen/
    - sh ./run_test2.sh cpp 2.INTERFACE

uml_INTERFACE:
  stage: uml
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test2.sh uml 2.INTERFACE

graph_INTERFACE:
  stage: graph
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test2.sh graph 2.INTERFACE

cpp_COMPONENT:
  stage: cpp
  tags:
    - python
  script:
    - cd Test/gen/
    - sh ./run_test2.sh cpp 3.COMPONENT

uml_COMPONENT:
  stage: uml
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test2.sh uml 3.COMPONENT

graph_COMPONENT:
  stage: graph
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test2.sh graph 3.COMPONENT

cpp_LINK:
  stage: cpp
  tags:
    - python
  script:
    - cd Test/gen/
    - sh ./run_test2.sh cpp 4.LINK

uml_LINK:
  stage: uml
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test2.sh uml 4.LINK

graph_LINK:
  stage: graph
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test2.sh graph 4.LINK



cpp_DEPLOYMENT:
  stage: cpp
  tags:
    - python
  script:
    - cd Test/gen/
    - sh ./run_test2.sh cpp 5.DEPLOYMENT

uml_DEPLOYMENT:
  stage: uml
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test2.sh uml 5.DEPLOYMENT

graph_DEPLOYMENT:
  stage: graph
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test2.sh graph 5.DEPLOYMENT

cpp_SWIG:
  stage: cpp
  tags:
    - python
  script:
    - cd Test/gen/
    - sh ./run_test2.sh cpp 8.SWIG
