stages:
  - generation

Generation_cpp_type:
  stage: generation
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test.sh cpp 0.TYPE
  artifacts:
    paths:
      - Test/gen/tmp

Generation_cpp_struct:
  stage: generation
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test.sh cpp 1.STRUCT
  artifacts:
    paths:
      - Test/gen/tmp

Generation_cpp_interface:
  stage: generation
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test.sh cpp 2.INTERFACE
  artifacts:
    paths:
      - Test/gen/tmp

Generation_cpp_component:
  stage: generation
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test.sh cpp 3.COMPONENT
  artifacts:
    paths:
      - Test/gen/tmp


Generation_cpp_link:
  stage: generation
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test.sh cpp 3.LINK
  artifacts:
    paths:
      - Test/gen/tmp


Generation_cpp_deployment:
  stage: generation
  tags:
    - python
  script:
    - cd Test/gen/
    - sh  ./run_test.sh cpp 4.DEPLOYMENT
  artifacts:
    paths:
      - Test/gen/tmp

