stages:
  - model_expand
  - model_detect

  - ExR_targer

  - CompoMe_Core
  - CompoMe_Opt
  - CompoMe_Link

  - cpp_clang
  - cpp_example
  - graph
  - uml
  - python

variables:
  CXX: "clang++"
  TERM: xterm
  GIT_SUBMODULE_STRATEGY: recursive

# ######################UML
include:
  - local: '/.gitlab-ci_model.yaml'
  - local: '/.gitlab-ci_core.yaml'
  - local: '/.gitlab-ci_cpp.yaml'
  - local: '/.gitlab-ci_graph.yaml'
  - local: '/.gitlab-ci_uml.yaml'
  - local: '/.gitlab-ci_python.yaml'

###################### CPP BEFORE
CompoMe_ExR:
  stage: CompoMe_ExR
  retry: 2
  tags:
    - python
  script:
    - export COMPOME_PATH=$(pwd) 
    - cd Test/gen
    - COMPOME_MODEL=CPP ./core_build_exr.sh
  artifacts:
    paths:
      - ./build

