@startuml

class Component {
  + Component()
  + virtual ~Component()
  + virtual void configuration()
  + virtual void connection()
  + virtual void start()
  + virtual void step()
  + virtual void stop()
  + virtual void status()
}

{% for component in MAIN.COMPONENTS.values() %}
Class {{component.D_NAME}} {
{% for d in component.DATA -%}
   {{d.TYPE.D_NAME}} {{d.NAME}}
{% endfor -%}
{% for f in component.FUNCTION -%}
   {{f.RETURN.D_NAME}} {{f.NAME}}(
   {%- for p in f.SIGNATURE -%}
   {{p.TYPE.D_NAME}} {{p.NAME}}{%if not loop.last%},{%endif%}
   {%- endfor -%})
{% endfor -%}
{% for p in component.PROVIDE -%}
{%if loop.first %}__ Provide __
{%endif-%}
   {{p.INTERFACE.D_NAME}}_{{p.NAME}} {{p.NAME}}
{% endfor -%}
{% for r in component.REQUIRE -%}
{%if loop.first %}__ Require __
{%endif-%}
   {{r.INTERFACE.D_NAME}} {{r.NAME}}
{% endfor -%}
{% for sc in component.COMPONENT_INSTANCE -%}
{%if loop.first %}__ SUB COMPONENT __
{%endif-%}
   {{sc.COMPONENT.D_NAME}} {{sc.NAME}}
{% endfor -%}
}

{% if "PARENT" in component %}
{{component.PARENT.D_NAME}} <|-- {{component.D_NAME}}
{% else %}
Component <|-- {{component.D_NAME}}
{% endif %}
{%endfor%}
@enduml
