@startuml

class Deployment {
   - std::vector<Link*> links
   - std::vector<Component*> components
   + void init()
   + void configuration()
   + void link()
   + void start()
   + void step()
   + void stop()
   + void quit()
}

{% for deployment in MAIN.DEPLOYMENTS.values() %}
Class {{deployment.D_NAME}} {
{% for d in deployment.DATA -%}
   {{d.TYPE.D_NAME}} {{d.NAME}}
{% endfor -%}
__ COMPONENT __
{% for i in deployment.INSTANCE -%}
   {{i.COMPONENT.D_NAME}} {{i.NAME}}
{% endfor -%}
__ LINK __
{% for l in deployment.LINK_INSTANCE -%}
   {{l.TYPE.D_NAME}} {{l.NAME}}
{% endfor -%}
}

{% if "PARENT" in deployment %}
{{deployment.PARENT.D_NAME}} <|-- {{deployment.D_NAME}}
{% else %}
Deployment <|-- {{deployment.D_NAME}}
{% endif %}


{% endfor %}
@enduml
