@startuml
namespace CompoMe {
Class Error
}

{% for err in MAIN.ERRORS.values() %}
{% if err.NAMESPACE != "" %}
namespace {{err.NAMESPACE.replace("::",".")}} {
{% endif %}
Class {{err.NAME}} {
{% for d in err.DATA -%}
   {{d.TYPE.NAME}} {{d.NAME}}
{% endfor %}
}

{% if "PARENT" in err %}
{{err.PARENT.D_NAME.replace("::",".")}} <|-- {{err.D_NAME.replace("::",".")}}
{% else %}
CompoMe.Error <|-- {{err.D_NAME.replace("::",".")}}
{% endif %}

{% if err.NAMESPACE != "" %}
}
{% endif %}
{% endfor %}
@enduml
