@startuml
namespace CompoMe {
Class Interface {
  + Interface();
  + virtual ~Interface();
  + virtual Caller* get_caller() = 0;
}
}

{% for interface in MAIN.INTERFACES.values() %}
{% if interface.NAMESPACE != "" %}
namespace {{interface.NAMESPACE.replace("::",".")}} {
{% endif %}
Class {{interface.NAME}} #FFFFFF {
{% for d in interface.DATA -%}
   {{d.TYPE.D_NAME}} {{d.NAME}}
{% endfor %}
{% for f in interface.FUNCTION -%}
   {{f.RETURN.D_NAME}} {{f.NAME}}(
   {%- for p in f.SIGNATURE -%}
   + {{p.TYPE.D_NAME}} {{p.NAME}}{%if not loop.last%},{%endif%}
   {%- endfor -%})
{% endfor -%}
}


Class {{interface.NAME}}_fake #FFDDDD {
      + {{interface.NAME}}_fake(Function_stream, Return_stream)
}

{{interface.D_NAME.replace("::",".")}} <|-- {{interface.D_NAME.replace("::",".")}}_fake

{% if interface.OPTIONS and interface.OPTIONS.FAKE_DBUS%}
Class {{interface.NAME}}_fake_dbus #FFDDDD {}
{{interface.D_NAME.replace("::",".")}} <|-- {{interface.D_NAME.replace("::",".")}}_fake_dbus
{%endif%}

{% if interface.OPTIONS and interface.OPTIONS.FAKE_JSON%}
Class {{interface.NAME}}_fake_json #FFDDDD {}
{{interface.D_NAME.replace("::",".")}} <|-- {{interface.D_NAME.replace("::",".")}}_fake_json
{%endif%}


Class {{interface.NAME}}_caller #DDFFDD {
      + {{interface.NAME}}_caller()
      + ~{{interface.NAME}}_caller()
      + bool call(Function_stream &is, Return_stream &os)
}

{{interface.D_NAME.replace("::",".")}} *-- {{interface.D_NAME.replace("::",".")}}_caller

{% if interface.OPTIONS and interface.OPTIONS.CALLER_JSON%}
Class {{interface.NAME}}_caller_json #DDFFDD {
      + {{interface.NAME}}_caller_json()
      + ~{{interface.NAME}}_caller_json()
}

{{interface.D_NAME.replace("::",".")}} *-- {{interface.D_NAME.replace("::",".")}}_caller_json
{%endif%}

{% if interface.OPTIONS and interface.OPTIONS.CALLER_DBUS%}
Class {{interface.NAME}}_caller_dbus #DDFFDD {
      + {{interface.NAME}}_caller_dbus()
      + ~{{interface.NAME}}_caller_dbus()
}
{{interface.D_NAME.replace("::",".")}} *-- {{interface.D_NAME.replace("::",".")}}_caller_dbus
{%endif%}

{% if "PARENT" in interface %}
{{interface.PARENT.D_NAME.replace("::",".")}} <|-- {{interface.D_NAME.replace("::",".")}}
{% else %}
CompoMe.Interface <|-- {{interface.D_NAME.replace("::",".")}}
{% endif %}

{% if interface.NAMESPACE != "" %}
}
{% endif %}
{% endfor %}

{% for m in MAIN.COMPONENTS.values() %}
{% for p in m.PROVIDE %}
namespace {{m.D_NAME.replace("::",".")}} {
class {{p.INTERFACE.NAME}}_{{p.NAME}} #DDFFDD {
      - {{m.D_NAME}}::{{m.NAME}} c
}
}
{{p.INTERFACE.D_NAME.replace("::",".")}} <|-- {{m.D_NAME.replace("::",".")}}.{{p.INTERFACE.NAME}}_{{p.NAME}}
{% endfor %}
{% endfor %}

@enduml
