{% if "COMPONENT_INSTANCE" in component %}
{% for sc in component.COMPONENT_INSTANCE%}
{{component.NAME}} --* {{sc.COMPONENT.NAME}} : {{sc.NAME}}
{%endfor%}
{%endif-%}

{%if "PARENT" in component %}
{%with component=component.PARENT%}
{% include "uml/sc_include.puml" %}
{%endwith%}
{%endif%}