@startuml
namespace CompoMe {
Class Struct
}
{% for struct in MAIN.STRUCTS.values() %}
{% if struct.NAMESPACE != "" %}
namespace {{struct.NAMESPACE.replace("::",".")}} {
{% endif %}
Class {{struct.NAME}} {
{% for d in struct.DATA -%}
   {{d.TYPE.D_NAME}} {{d.NAME}}
{% endfor %}
}
{% if struct.NAMESPACE  != "" %}
}
{% endif %}

{% if "PARENT" in struct %}
{{struct.PARENT.D_NAME.replace("::",".")}} <|-- {{struct.D_NAME.replace("::",".")}}
{% else %}
CompoMe.Struct <|-- {{struct.D_NAME.replace("::",".")}}
{% endif %}

{% set include_key = [] %}
{% for d in struct.DATA %}

{% if Function.model_test.is_struct(d.TYPE.D_NAME, MAIN) %}

{%- if d.TYPE.D_NAME not in include_key -%}
{{struct.D_NAME}} *-- {{d.TYPE.D_NAME}}
{% set _ = include_key.append(d.TYPE.D_NAME) -%}
{% endif %}
{% endif %}
{% endfor %}

{% endfor %}
@enduml
