########################### DEPLOIMENT ###################################

- NAME: Deployment
  TARGET_NAME: "DEPLOYMENT.BASE"
  FOR: "DEPLOYMENTS"
  DEFAULT:
    FILE: "MODEL:NAME"
  FILES:
    - IN:  "Deployments/Deployment_parent.hpp"
      OUT: "inc/Deployments/Deployment.hpp"
    - IN:  "Deployments/Deployment_parent.cpp"
      OUT: "src/Deployments/Deployment.cpp"
  COMMANDS:
    - "clang-format -i src/Deployments/Deployment.cpp "
    - "clang-format -i inc/Deployments/Deployment.hpp "

- NAME: Deployments_get_set
  TARGET_NAME: "DEPLOYMENT.{{D_NAME}}.GET_SET"
  FOR: "DEPLOYMENTS.*"
  DEFAULT:
    FILE : "MODEL:NAME"
  FILES:
    - IN:  "Deployments/Deployment_template_get_set.cpp"
      OUT: "src/Deployments/{{F_NAME}}/{{NAME}}_get_set.cpp"
  COMMANDS:
    - "clang-format -i src/Deployments/{{F_NAME}}/{{NAME}}_get_set.cpp "

- INCLUDE: "generation_deployment_base.yaml"
- INCLUDE: "generation_deployment_swig.yaml"
