########################### DEPLOIMENT ###################################
- NAME: Deployment
  TARGET_NAME: "DEPLOYMENT.BASE"
  FOR: "DEPLOYMENTS"
  DEFAULT:
    FILE: "MODEL:FILE"
  FILES:
    - IN: Deployments/Deployment_parent.hpp
      OUT: "inc/Deployments/Deployment.hpp"
    - IN: Deployments/Deployment_parent.cpp
      OUT: "src/Deployments/Deployment.cpp"
  COMMANDS:
    - "clang-format -i src/Deployments/Deployment.cpp"
    - "clang-format -i inc/Deployments/Deployment.hpp"

- NAME: Deployments
  FOR: "DEPLOYMENTS.*"
  TARGET_NAME: "DEPLOYMENT.{{D_NAME}}"
  DEFAULT:
    FILE : "MODEL:FILE"
  FILES:
    - IN: Deployments/Deployment_template.hpp
      OUT: "inc/Deployments/{{F_NAME}}/{{NAME}}.hpp"
    - IN: Deployments/Deployment_template.cpp
      OUT: "src/Deployments/{{F_NAME}}/{{NAME}}.cpp"
  COMMANDS:
    - "clang-format -i inc/Deployments/{{F_NAME}}/{{NAME}}.hpp"
    - "clang-format -i src/Deployments/{{F_NAME}}/{{NAME}}.cpp"
