########################### DEPLOIMENT ###################################
- NAME: Deployment
  TARGET_NAME: "DEPLOYMENT.BASE"
  FOR: "DEPLOYMENTS"
  DEFAULT:
    FILE: "MODEL:NAME"
  FILES:
    - IN:  "Deployments/Deployment_parent.hpp"
      OUT: "inc/Deployments/Deployment.hpp"
    - IN:  "Deployments/Deployment_parent.cpp"
      OUT: "src/Deployments/Deployment.cpp"
  COMMANDS:
    - "clang-format -i src/Deployments/Deployment.cpp "
    - "clang-format -i inc/Deployments/Deployment.hpp "

- NAME: Deployments
  TARGET_NAME: "DEPLOYMENT.{{D_NAME}}"
  FOR: "DEPLOYMENTS.*"
  DEFAULT:
    FILE : "MODEL:NAME"
  FILES:
    - IN:  "Deployments/Deployment_template.hpp"
      OUT: "inc/Deployments/{{F_NAME}}/{{NAME}}.hpp"
    - IN:  "Deployments/Deployment_template.cpp"
      OUT: "src/Deployments/{{F_NAME}}/{{NAME}}.cpp"
  COMMANDS:
    - "clang-format -i inc/Deployments/{{F_NAME}}/{{NAME}}.hpp "
    - "clang-format -i src/Deployments/{{F_NAME}}/{{NAME}}.cpp "

- NAME: Deployments_get_set
  TARGET_NAME: "DEPLOYMENT.{{D_NAME}}.GET_SET"
  FOR: "DEPLOYMENTS.*"
  DEFAULT:
    FILE : "MODEL:NAME"
  FILES:
    - IN:  "Deployments/Deployment_template_get_set.cpp"
      OUT: "src/Deployments/{{F_NAME}}/{{NAME}}_get_set.cpp"
  COMMANDS:
    - "clang-format -i src/Deployments/{{F_NAME}}/{{NAME}}_get_set.cpp "

- NAME: Deployment_Swig
  TARGET_NAME: "DEPLOYMENT.BASE.SWIG"
  FOR: "DEPLOYMENTS"
  FILES:
    - IN:  "Deployments/Deployment.i"
      OUT: "swig/Deployments/Deployment.i"

- NAME: Deploiments_Swig
  TARGET_NAME: "DEPLOIMENT.SWIG.{{D_NAME}}"
  FOR: "DEPLOYMENTS.*"
  DEFAULT:
    MAIN : "MODEL:."
    FILE : "MODEL:NAME"
  IF:
    OPTIONS.SWIG: true
  FILES:
    - IN:  "Deployments/Deployment_template.i"
      OUT: "swig/Deployments/{{F_NAME}}.i"
