@startuml

class Deployment {
   - std::vector<Link*> links
   - std::vector<Component*> components
   + void init()
   + void configuration()
   + void link()
   + void start()
   + void step()
   + void stop()
   + void quit()
}


Class D_t1 {
__ COMPONENT __
C_t2r c1r
C_t2p c1p
__ LINK __
}


Deployment <|-- D_t1




Class D_t2 {
__ COMPONENT __
__ LINK __
Simple s0
}


D_t1 <|-- D_t2




Class D_t3 {
__ COMPONENT __
C_t2r r2
C_t2r r3
C_t1r r4
C_n r5
__ LINK __
Simple s1
Simple s2
Simple s3
Simple s4
Out_link lo1
Out_link lo2
In_link li1
In_link li2
}


D_t2 <|-- D_t3




@enduml